language: generic
sudo: required

services:
 - docker

before_install:
 - docker build -f Dockerfile.dev -t docker-react .

script:
  - docker run -e CI=true docker-react npm run test


deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-react-test"
  env: "docker-react-test"
  bucket_name: ""
  bucket_path: ""
  on:
    branch: "master"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY